#!/bin/bash
# count instance script

grep "Solve " console_ndiff_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv
grep "Solve " console_ndiff_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Solve.csv

grep "Solve " console_iqs_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv
grep "Solve " console_iqs_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Solve.csv

grep "Solve " console_iqstmp_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv
grep "Solve " console_iqstmp_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Solve.csv

grep "Solve " console_ndiff2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv
grep "Solve " console_ndiff2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Solve.csv

grep "Solve " console_iqs2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv
grep "Solve " console_iqs2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Solve.csv

grep "Solve " console_iqstmp2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv
grep "Solve " console_iqstmp2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Solve.csv

grep "Solve " console_ndiff_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Solve.csv

grep "Solve " console_iqs_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Solve.csv

grep "Solve " console_iqstmp_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Solve.csv

grep "Solve " console_ndiff2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv
grep "Solve " console_ndiff2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Solve.csv

grep "Solve " console_iqs2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqs2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Solve.csv

grep "Solve " console_iqstmp2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv
grep "Solve " console_iqstmp2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Solve.csv

grep "Linear " console_ndiff_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv
grep "Linear " console_ndiff_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Linear.csv

grep "Linear " console_iqs_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv
grep "Linear " console_iqs_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Linear.csv

grep "Linear " console_iqstmp_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv
grep "Linear " console_iqstmp_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Linear.csv

grep "Linear " console_ndiff2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv
grep "Linear " console_ndiff2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Linear.csv

grep "Linear " console_iqs2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv
grep "Linear " console_iqs2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Linear.csv

grep "Linear " console_iqstmp2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv
grep "Linear " console_iqstmp2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Linear.csv

grep "Linear " console_ndiff_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Linear.csv

grep "Linear " console_iqs_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Linear.csv

grep "Linear " console_iqstmp_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Linear.csv

grep "Linear " console_ndiff2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv
grep "Linear " console_ndiff2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Linear.csv

grep "Linear " console_iqs2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqs2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Linear.csv

grep "Linear " console_iqstmp2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv
grep "Linear " console_iqstmp2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Linear.csv

grep "Nonlinear " console_ndiff_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_1D_Nonlinear.csv

grep "Nonlinear " console_iqs_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv
grep "Nonlinear " console_iqs_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_1D_Nonlinear.csv

grep "Nonlinear " console_iqstmp_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_1D_Nonlinear.csv

grep "Nonlinear " console_ndiff2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv
grep "Nonlinear " console_ndiff2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_1D_Nonlinear.csv

grep "Nonlinear " console_iqs2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv
grep "Nonlinear " console_iqs2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_1D_Nonlinear.csv

grep "Nonlinear " console_iqstmp2_1D_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_1D_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_1D_Nonlinear.csv

grep "Nonlinear " console_ndiff_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff_TWIGL_ramp_Nonlinear.csv

grep "Nonlinear " console_iqs_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs_TWIGL_ramp_Nonlinear.csv

grep "Nonlinear " console_iqstmp_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp_TWIGL_ramp_Nonlinear.csv

grep "Nonlinear " console_ndiff2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_ndiff2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> ndiff2_TWIGL_ramp_Nonlinear.csv

grep "Nonlinear " console_iqs2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqs2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqs2_TWIGL_ramp_Nonlinear.csv

grep "Nonlinear " console_iqstmp2_TWIGL_ramp_00.txt | grep -v initial| grep -v adjoint|wc -l > iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_01.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_02.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_03.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_04.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_05.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_06.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_07.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_08.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_09.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
grep "Nonlinear " console_iqstmp2_TWIGL_ramp_10.txt | grep -v initial| grep -v adjoint|wc -l >> iqstmp2_TWIGL_ramp_Nonlinear.csv
